live_config_reload = true
# tabspaces = 2
# theme = "Atelierlakeside.dark"

[shell]
args = ["-l"]
program = "/bin/zsh"

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "transparent"
dynamic_padding = false
opacity = 0.9
startup_mode = "Maximized"

[window.dimensions]
columns = 120
lines = 60

[window.padding]
x = 10
y = 30

[colors]
# author = "Chris Kempson"
# name = "Atelierlakeside (dark)"

[colors.bright]
black = "#5a7b8c"
blue = "#257fad"
cyan = "#2d8f6f"
green = "#568c3b"
magenta = "#5d5db1"
red = "#d22d72"
white = "#ebf8ff"
yellow = "#8a8a0f"

[colors.cursor]
cursor = "#7ea2b4"
text = "#161b1d"

[colors.normal]
black = "#161b1d"
blue = "#257fad"
cyan = "#2d8f6f"
green = "#568c3b"
magenta = "#5d5db1"
red = "#d22d72"
white = "#7ea2b4"
yellow = "#8a8a0f"

[colors.primary]
background = "#161b1d"
foreground = "#7ea2b4"

[font]
size = 10

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Command"

[scrolling]
# auto_scroll = true
# faux_multiplier = 100
history = 2000
multiplier = 20
